[zos-console] Added method to get a command response
zowe/zowe-client-python-sdk pull request #102
Opened 2022-07-29 17:37 UTC by aadityasinha-dotcom

Added a method to call the z/OSMF REST API `GET /zosmf/restconsoles/consoles/<console-name>/solmsgs/C<key-number>`
Signed-off-by: Aaditya Sinha [aadityasinha009@gmail.com](mailto:aadityasinha009@gmail.com)

2022-09-06 19:25 UTC, zFernand0 requested changes
hey @aadityasinha-dotcom 
I see a few things that can be improved.

Here is a summary of the changes I'm thinking of:
https://github.com/aadityasinha-dotcom/zowe-client-python-sdk/compare/get_command...zowe:zowe-client-python-sdk:fix-console-apis

1. Help text change.
    - the get_response is not exactly getting any response of a console command, it's more collecting operator-type messages that are still outstanding (i.e. left to be replied/responded to)
2. `solmsgs` should be optional, and likely be renamed to `console` 
3. it seems that the `defcn` in the url is preventing us to use the given console name.

FYI, there has to be a better way to handle the `defcn` vs console-name issue 😋 
The compare URL is there to serve as a working example 😋

2022-09-15 18:06 UTC, zFernand0 reviewed
Thanks for addressing the requested changes.
I left one more comment.

Also, do you think we could have some tests added ?

2022-09-15 18:06 UTC, zFernand0 commented on src/zos_console/zowe/zos_console_for_zowe_sdk/console.py
> +        custom_args["data"] = request_body
I believe this part here might be redundant 😋

2022-09-19 15:04 UTC, zFernand0 commented
Please address the DCO sign-off issues in addition to the changes requested.

2022-09-21 14:53 UTC, zFernand0 requested changes
LGTM!
Just waiting on DCO fixes and some tests! 🥳

2022-09-21 14:54 UTC, aadityasinha-dotcom commented
Sorry will do dco been sick for few days

2022-09-26 15:56 UTC, aadityasinha-dotcom commented
Recreated this PR https://github.com/zowe/zowe-client-python-sdk/pull/142

2022-09-26 15:56 UTC, closed without merging