[zos-jobs] Added support for `cancel_job` version number on requests
zowe/zowe-client-python-sdk pull request #106
Opened 2022-08-11 04:33 UTC by aadityasinha-dotcom

Added an optional `modifyVersion` parameter to the `cancel_job` API with a default value of `"2.0"`

2022-08-29 19:48 UTC, t1m0thyj commented
@aadityasinha-dotcom Thanks for your contribution 🙂 Please add unit and integration tests for the `cancel_job` API modeled after the ones you wrote in #97.

2022-09-14 17:55 UTC, zFernand0 requested changes
Thanks for working on this.
I left some comments that could improve the overall usage of the API 😋 

One additional consideration.
There are some z/OSMF REST APIs that don't return all headers if the response is empty.
For that reason, maybe we should consider the following small change too: 
From `self.response.headers['Content-Type']` to `self.response.headers.get('Content-Type')` in 
`src/core/zowe/core_for_zowe_sdk/request_handler.py`

(Thanks @t1m0thyj for helping me understand what was happening)

2022-09-14 17:55 UTC, zFernand0 commented on src/zos_jobs/zowe/zos_jobs_for_zowe_sdk/jobs.py
> +        response_json = self.request_handler.perform_request("PUT", custom_args, expected_code=[202])
Please remove the duplicate REST calls and use `202, 200` for the `expected_code`.

2022-09-19 14:08 UTC, t1m0thyj commented
Looks like this enhancement was already made in #124. Sorry about that 😢 Going forward, we can avoid this happening again by making sure to assign issues to avoid duplicate work 🙂

2022-09-19 14:08 UTC, closed without merging

2022-09-19 14:34 UTC, aadityasinha-dotcom commented
> Looks like this enhancement was already made in #124. Sorry about that 😢 Going forward, we can avoid this happening again by making sure to assign issues to avoid duplicate work 🙂

No worries