Added method to migrate data set.
zowe/zowe-client-python-sdk pull request #121
Opened 2022-08-26 13:27 UTC by antondelchev

Signed-off-by: Anton Delchev <dlchv.mail@gmail.com>

2022-08-26 19:16 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +        response_json = self.request_handler.perform_request("PUT", custom_args, expected_code=[204])
The expected response code should be 200.

2022-08-29 19:54 UTC, t1m0thyj approved these changes

2022-09-09 08:18 UTC, boris-bc requested changes

2022-09-09 08:18 UTC, boris-bc commented on tests/unit/test_zos_files.py
> +    def test_migrate_data_set(self, mock_send_request):
There is no assertion in this test. What is its purpose?

2022-09-09 08:37 UTC, boris-bc approved these changes

2022-09-09 08:39 UTC, merged