update workflows - next
zowe/zowe-client-python-sdk pull request #151
Opened 2023-05-08 14:22 UTC by ATorrise

Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)

2023-05-08 18:05 UTC, zFernand0 requested changes

2023-05-08 18:05 UTC, zFernand0 commented on .github/workflows/dev-release.yaml
Can we also update the following:
- `actions/setup-python@v2` -> `actions/setup-python@v4`

2023-05-08 18:05 UTC, zFernand0 commented on .github/workflows/sdk-build.yml
>        uses: actions/setup-python@v2
same as with the other workflow, `actions/setup-python@v4`

2023-05-12 20:21 UTC, t1m0thyj approved these changes
LGTM, thanks @ATorrise!

The ReadTheDocs build failure is unrelated to this PR so I think we can fix it separately 🙂

2023-05-12 20:21 UTC, merged