fixed issue #63 Added methods to copy (dataset or member) & USS files
zowe/zowe-client-python-sdk pull request #184
Opened 2023-06-08 12:38 UTC by samadpls

**What It Does**

add method `copy_dataset_or_member`
Resolve issue #63  

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [ ] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2023-06-09 15:28 UTC, t1m0thyj requested changes
Thanks @samadpls 🙂 Left a few comments about the function parameters

2023-06-09 15:28 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +                If true, the function uses the REPLACE=YES on ARCHDEF request, otherwise it uses the REPLACE=NO.
Not everyone will be familiar with what an ARCHDEF request is. For the replace option I think we'll want to say something like the following:
`If true, members in the target data set are replaced.`

2023-06-09 15:28 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +        path_to_member = f"{to_dataset_name.strip()}({to_member_name.strip()})" if to_member_name else to_dataset_name.strip()
I don't think it's necessary to `strip` all of the input strings. We can either assume that the user has provided strings without extra spaces, or that if there are any the REST API will handle them.

2023-06-09 15:28 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +                               to_member_name="",enq="",replace=False):
For the default value of `from_member_name`, `to_member_name`, `volser`, `alias`, and `enq`, can we use `None` instead of an empty string?

2023-06-09 15:28 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +                If true, the function uses the REPLACE=YES on ARCHDEF request, otherwise it uses the REPLACE=NO.
Same comment as above about the docs for the `replace` option

2023-06-09 15:28 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +            data["from-dataset"]["alias"]=alias.strip()
Not necessary to strip all of the input strings (same comment as above).

2023-06-10 04:06 UTC, samadpls commented
@t1m0thyj , thank you for your comments. I have updated the PR.

2023-06-19 19:09 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +                               to_member_name=None,enq=None,replace=False):
Discussed with @zFernand0, and we do want keep all the parameters as they were defined before.

Could you please restore the full method signature?
`def copy_dataset_or_member(self, from_dataset_name, to_dataset_name, from_member_name=None, volser=None, alias=None, to_member_name=None, enq=None, replace=False):`

In the tests, we can continue using a dictionary to define the keyword args 👍

2023-06-19 19:56 UTC, t1m0thyj approved these changes

2023-06-19 19:57 UTC, zFernand0 approved these changes

2023-06-19 19:57 UTC, zFernand0 commented on src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
> +                               to_member_name=None,enq=None,replace=False):
Sorry for not commenting sooner. And thanks for summarizing the discussion

2023-06-20 16:19 UTC, merged