Update doc strings
zowe/zowe-client-python-sdk pull request #307
Opened 2024-07-08 19:16 UTC by pem70

**What It Does**
Update doc strings for all functions as required by [#279]

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-07-10 16:44 UTC, zFernand0 commented
Hey @anaxceron, 
Here is the live site with the changed that are in the main branch.
https://zowe-client-python-sdk.readthedocs.io/

We don't have the equivalent of Netlify for PR builds yet 😢 
But hopefully it helps. 😋

2024-07-15 14:43 UTC, t1m0thyj requested changes
Looks pretty good, thanks @pem70!

Left minor comments related to consistency and documenting the `encoding` option.

2024-07-15 14:43 UTC, t1m0thyj commented on CHANGELOG.md
> +- Updated all functions descriptions to be consitent [#279] (https://github.com/zowe/zowe-client-python-sdk/issues/279)
```suggestion
- Updated doc strings for all functions to be consistent [#279] (https://github.com/zowe/zowe-client-python-sdk/issues/279)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
> +            Specifies encoding schema
```suggestion
            Specifies encoding name (e.g. IBM-1047)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
> +            If true, include a four big endian bytes record length prefix. The default is False
Should we use formatting consistent with `get_binary_content`?
```suggestion
            If true, include a four big endian bytes record length prefix. Default: False
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
> +            Specifies the encoding schema
```suggestion
            Specifies the encoding name (e.g. IBM-1047)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/file_system.py
> +            specifies file system attributes
I think we should use sentence case to make the descriptions consistent
```suggestion
        file_system_name: str
            Name of the file system
        options: dict
            Specifies file system attributes
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/file_system.py
> +            Specifies optional encoding schema
```suggestion
            Specifies optional encoding name (e.g. IBM-1047)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/file_system.py
> +            Specifies optional encoding schema
```suggestion
            Specifies optional encoding name (e.g. IBM-1047)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/file_system.py
> +            the name for the file system to be listed
Same comment as above about sentence case for consistency
```suggestion
        file_path: str
            USS directory that contains the files and directories to be listed
        file_system_name: str
            Name of the file system to be listed
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/uss.py
> +            filepath of the file to be deleted
```suggestion
            Path of the file to be deleted
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/uss.py
> +            Ex:- rwxr-xr-x
```suggestion
        file_path: str
            Path of the file to add
        type: str
            Specify either "file" or "dir"
        mode: str
            Unix permission string (e.g. `rwxr-xr-x`)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/uss.py
> +            Specifies the encoding schema
```suggestion
            Specifies the encoding name (e.g. IBM-1047)
```

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
> +            The member attributes to retrieve.
Trailing periods should be removed for consistency

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
>              If true, members in the target data set are replaced.
Trailing periods should be removed for consistency

2024-07-15 14:43 UTC, t1m0thyj commented on src/zos_files/zowe/zos_files_for_zowe_sdk/datasets.py
> +            Specifies
```suggestion
            Specify True to return content as a stream object instead of a string. Default: False
```

2024-07-15 18:44 UTC, pem70 commented
Merged into a combined pull request.

2024-07-15 18:44 UTC, closed without merging