update readme
zowe/zowe-client-python-sdk pull request #340
Opened 2024-10-20 14:44 UTC by olamidepeterojo

**What It Does**
Updated typo in README

Fixes #326 

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-10-21 13:23 UTC, zFernand0 commented
closing in favor of #341 (since it contains the same changes)

2024-10-21 13:28 UTC, zFernand0 requested changes
Hey @olamidepeterojo,
Please make sure to signoff your commits 😋 

To add your Signed-off-by line to every commit in this branch:

1. Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
2. In your local branch, run: `git rebase HEAD~1 --signoff`
3. Force push your changes to overwrite the branch: `git push --force-with-lease origin readme-update`

2024-10-21 15:03 UTC, olamidepeterojo commented
Thank you for the kind gesture and efforts in going through my PR... Will do accordingly

2024-10-21 16:58 UTC, zFernand0 approved these changes
LGTM! 😋

2024-10-25 14:29 UTC, olamidepeterojo commented
Added the fix for this issue #328 to this PR

2024-10-28 14:01 UTC, zFernand0 requested changes
Thanks for updating the readme as well.

I see that license headers have `Zowe Python Client SDK`

For a quick fix,  I suggest doing a find-and-replace with your IDE.

Otherwise, you may need to enhance the existing `scripts/license_header.py` script to account for license header updates 😓

2024-10-28 14:50 UTC, olamidepeterojo commented on CHANGELOG.md
> +- Therefore this fixes issue #328
okay, your suggestion is good, let me get it done right away

2024-10-28 15:05 UTC, zFernand0 requested changes

2024-10-28 15:05 UTC, zFernand0 commented on CHANGELOG.md
> +Fixed the inconsistent use of the SDK name across SDKs in all files by implementing the "find and replace" tool. [#328](https://github.com/zowe/zowe-client-python-sdk/issues/328)
```suggestion
- Fixed the inconsistent use of the SDK name across SDKs in all files by implementing the "find and replace" tool. [#328](https://github.com/zowe/zowe-client-python-sdk/issues/328)
```
Not sure what happened with the bullet point here 😅 
Sorry for being picky 😋

2024-10-28 15:06 UTC, zFernand0 commented on CHANGELOG.md
> +Fixed the inconsistent use of the SDK name across SDKs in all files by implementing the "find and replace" tool. [#328](https://github.com/zowe/zowe-client-python-sdk/issues/328)
```suggestion
- Fixed exception handling in session.py [#213](https://github.com/zowe/zowe-client-python-sdk/issues/213)
- Fixed the inconsistent use of the SDK name across SDKs in all files by implementing the "find and replace" tool. [#328](https://github.com/zowe/zowe-client-python-sdk/issues/328)
```

2024-10-28 16:39 UTC, zFernand0 requested changes
Because of all the force-push, I'm unable to determine when the changelog entry was added in 1.0.0-dev.11 instead of the Recent Changes. 😢 

Would you mind moving it to the very top?

```markdown
## Recent Changes

### Enhancements

- Turning of logger at the class-constructor level [#316] (https://github.com/zowe/zowe-client-python-sdk/issues/316)

### Bug Fixes

- Fixed the inconsistent use of the SDK name across SDKs in all files by implementing the "find and replace" tool. [#328](https://github.com/zowe/zowe-client-python-sdk/issues/328)

## `1.0.0-dev21`
```

2024-10-28 18:46 UTC, zFernand0 approved these changes
LGTM! 😋

2024-10-28 19:01 UTC, olamidepeterojo commented
hey @zFernand0 , seems like you got it done already haha. would you still be needing i make the same changes?

2024-10-28 19:16 UTC, zFernand0 commented
> hey `@zFernand0` , seems like you got it done already haha. would you still be needing i make the same changes?

Hey @olamidepeterojo,
I felt that I was being super annoying so that's why I tried to help out for once 😅 
Apologies for all the requested changes...

And to answer you question, No.
I think there are no mo changes required/needed in order to get this PR merged in 🙏 

Thanks for all the hard work 🙏 

We just need one more review from the team before we get it merged 🥳

2024-10-28 19:29 UTC, merged

2024-10-28 21:26 UTC, olamidepeterojo commented
its no hassle @zFernand0 its nice working with you and its my pleasure.

could you kindly check my PR of issue #336. ive been waiting your review haha.